# Generated by Django 5.0.6 on 2024-12-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0003_product_barcode_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
    ]
