# Generated by Django 5.0.6 on 2024-12-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0006_salesemployee_country_salesemployee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesemployee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
