# Generated by Django 5.0.6 on 2024-12-22 05:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0007_salesemployee_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
