# Generated by Django 5.0.6 on 2024-12-22 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0009_arinvoice_sales_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoice',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='uniworlderp.salesorder'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='uniworlderp.product'),
        ),
        migrations.AddConstraint(
            model_name='arinvoice',
            constraint=models.UniqueConstraint(fields=('sales_order',), name='unique_sales_order_invoice'),
        ),
    ]
