# Generated by Django 5.1.3 on 2024-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0012_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home', 'Home'), ('Toys', 'Toys')], default='Electronics', help_text='Select a category for the product.', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
