# Generated by Django 5.1.3 on 2024-12-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0013_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
