# Generated by Django 5.1.4 on 2024-12-23 14:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0016_alter_purchaseorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': ' Purchase Order', 'verbose_name_plural': ' Purchase Orders'},
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='uniworlderp_order_d_612de3_idx',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vendor',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_status',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='uniworlderp.product'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'order_date'], name='uniworlderp_supplie_0d8438_idx'),
        ),
    ]
