# Generated by Django 5.1.4 on 2024-12-23 14:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0017_alter_purchaseorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='uniworlderp_supplie_0d8438_idx',
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='total_amount',
            new_name='total',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Received')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date', 'delivery_status'], name='uniworlderp_order_d_612de3_idx'),
        ),
    ]
