# Generated by Django 5.1.4 on 2024-12-25 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0018_remove_purchaseorder_uniworlderp_supplie_0d8438_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoice',
            name='invoice_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
