# Generated by Django 5.1.4 on 2024-12-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0019_alter_arinvoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Chemical', 'Chemical'), ('RawMaterials', 'Raw Materials'), ('Others', 'Others')], default='Electronics', help_text='Select a category for the product.', max_length=50),
        ),
    ]
