# Generated by Django 5.1.4 on 2024-12-25 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0020_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoice',
            name='due_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
