# Generated by Django 5.1.4 on 2025-01-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0022_materialspurchase_materialspurchaseitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialspurchase',
            name='owner',
        ),
        migrations.AlterField(
            model_name='materialspurchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
