# Generated by Django 5.1.4 on 2025-03-12 06:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0023_remove_materialspurchase_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment'), ('RET', 'Return')], max_length=3),
        ),
        migrations.CreateModel(
            name='ReturnSales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to=settings.AUTH_USER_MODEL)),
                ('sales_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_items_process_person', to='uniworlderp.salesemployee')),
                ('salesorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='uniworlderp.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'verbose_name_plural': 'Sales Returns',
            },
        ),
        migrations.CreateModel(
            name='ReturnSalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniworlderp.product')),
                ('return_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='uniworlderp.returnsales')),
                ('salesorder_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='uniworlderp.salesorderitem')),
            ],
            options={
                'verbose_name': 'Return Sales Item',
                'verbose_name_plural': 'Return Sales Items',
            },
        ),
        migrations.AddIndex(
            model_name='returnsales',
            index=models.Index(fields=['return_date'], name='uniworlderp_return__771b81_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsalesitem',
            index=models.Index(fields=['return_sales', 'product'], name='uniworlderp_return__c5ccd0_idx'),
        ),
    ]
