# Generated by Django 5.1.4 on 2025-03-13 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0024_alter_stocktransaction_transaction_type_returnsales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnsalesitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='returnsalesitem',
            name='uniworlderp_return__c5ccd0_idx',
        ),
        migrations.RenameField(
            model_name='returnsales',
            old_name='total_return_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='returnsalesitem',
            old_name='return_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='returnsalesitem',
            old_name='salesorder_item',
            new_name='sales_order_item',
        ),
        migrations.RemoveField(
            model_name='returnsales',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='returnsales',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='returnsales',
            name='sales_employee',
        ),
        migrations.RemoveField(
            model_name='returnsales',
            name='salesorder',
        ),
        migrations.RemoveField(
            model_name='returnsalesitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnsalesitem',
            name='reason',
        ),
        migrations.AddField(
            model_name='returnsales',
            name='return_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to='uniworlderp.salesemployee'),
        ),
        migrations.AddField(
            model_name='returnsales',
            name='sales_order',
            field=models.ForeignKey(default=54654, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='uniworlderp.salesorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnsales',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='returnsales',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
