# Generated by Django 5.1.4 on 2025-04-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0025_alter_returnsalesitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsales',
            name='return_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to='uniworlderp.salesemployee'),
        ),
    ]
