# Generated by Django 5.1.4 on 2025-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0027_product_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount amount for the product.', max_digits=10, null=True),
        ),
    ]
