# Generated by Django 5.1.4 on 2025-05-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0028_salesorderitem_total_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='Unit_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount amount per unit for the product.', max_digits=10, null=True),
        ),
    ]
