# Generated by Django 5.1.4 on 2025-05-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0029_salesorderitem_unit_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
