# Generated by Django 5.1.4 on 2025-07-15 08:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0030_salesorder_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount to be subtracted from subtotal', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping amount to be added to subtotal after discount', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='remark',
            field=models.TextField(blank=True, help_text='Remarks for this product line', null=True),
        ),
    ]
