# Generated by Django 5.1.4 on 2025-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0031_salesorder_discount_salesorder_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock quantity after the transaction'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='previous_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock quantity before the transaction'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
