# Generated by Django 5.1.4 on 2025-07-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0032_stocktransaction_current_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='remark',
        ),
    ]
