# Generated by Django 5.1.4 on 2025-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0034_add_product_unit_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervendor',
            name='business_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('others', 'Others')], default='others', help_text='Select the business type for this customer/vendor.', max_length=20),
        ),
        migrations.AddField(
            model_name='customervendor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
