# Generated by Django 5.1.4 on 2025-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0036_set_default_customer_vendor_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customervendor',
            old_name='mobile_number',
            new_name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='customervendor',
            name='business_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('others', 'Others')], default='others', max_length=20, verbose_name='Business Type'),
        ),
    ]
