# Generated by Django 5.1.4 on 2026-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworlderp', '0038_make_phone_number_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervendor',
            name='area',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customervendor',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
